CREATE TABLE IF NOT EXISTS worker (
	id SERIAL PRIMARY key
);

CREATE TABLE IF NOT EXISTS workerinfo (
	name VARCHAR(40) NOT NULL,
	dep VARCHAR(3) NOT NULL,
	chief INTEGER NOT NULL REFERENCES worker(id)
);
